export const Colors = {
  normal: "peachpuff",
  grass: "mediumspringgreen",
  ground: "lightslategrey",
  fighting: "crimson ",
  rock: "dimgray",
  steel: "silver",
  fire: "firebrick",
  electric: "dodgerblue",
  flying: "#a890f0",
  psychic: "indigo",
  bug: "khaki",
  dragon: "coral",
  water: "mediumturquoise",
  ice: "royalblue",
  poison: "seagreen",
  dark: "black",
  ghost: "bisque",
  fairy: "lightcoral",
};